[project]
name = "trafficlightdetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "emilcode", email = "ephraim.eckl@posteo.de" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
trafficlightdetect = "trafficlightdetect:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
